/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;

import CLASES.Empleado;
import CLASES.Usuario;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JOptionPane;

/**
 *
 * @author termi
 */
public class frm_GestionarEmpleado extends javax.swing.JFrame {

    public frm_GestionarEmpleado() {
        initComponents();
        txtCurrentCedula.setEditable(false);
        txtNombre.setEditable(false);
        txtNombre2.setEditable(false);
        txtApellido.setEditable(false);
        txtApellido2.setEditable(false);
        cmbAño.setEnabled(true);
        cmbMes.setEnabled(true);
        cmbDia.setEnabled(true);
        txtDireccion.setEditable(false);
        txtTelefono.setEditable(false);
        btnGuardar.setEnabled(false);
        btnEditar.setEnabled(false);
        centreWindow(this);
    }

    public void emptyFields() {
        txtCurrentCedula.setText("");
        txtNombre.setText("");
        txtNombre2.setText("");
        txtApellido.setText("");
        txtApellido2.setText("");
        cmbAño.setSelectedIndex(0);
        cmbMes.setSelectedIndex(0);
        cmbDia.setSelectedIndex(0);
        txtDireccion.setText("");
        txtTelefono.setText("");
    }

    public void EnableFields() {
        txtNombre.setEditable(true);
        txtNombre2.setEditable(true);
        txtApellido.setEditable(true);
        txtApellido2.setEditable(true);
        cmbAño.setEnabled(true);
        cmbMes.setEnabled(true);
        cmbDia.setEnabled(true);
        txtDireccion.setEditable(true);
        txtTelefono.setEditable(true);
    }

    public void disableFields() {
        txtCurrentCedula.setEditable(false);
        txtNombre.setEditable(false);
        txtNombre2.setEditable(false);
        txtApellido.setEditable(false);
        txtApellido2.setEditable(false);
        cmbAño.setEnabled(true);
        cmbMes.setEnabled(true);
        cmbDia.setEnabled(true);
        txtDireccion.setEditable(false);
        txtTelefono.setEditable(false);

    }

    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchCedula = new javax.swing.JTextField();
        btnSearchEmpleado = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbAño = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbDia = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCurrentCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cedula");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 43, -1, -1));
        jPanel2.add(txtSearchCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 40, 229, -1));

        btnSearchEmpleado.setText("Buscar");
        btnSearchEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 40, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/WhatsApp Image 2022-06-25 at 6.39.58 PM.jpeg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 435, 90));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Empleador", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Primer Nombre");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Segundo Nombre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Primer Apellido");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Segundo Apellido");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Cedula");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));

        cmbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", " " }));
        cmbAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAñoActionPerformed(evt);
            }
        });
        jPanel3.add(cmbAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 20));

        cmbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        jPanel3.add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, 20));

        cmbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel3.add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 60, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Direccion");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Telefono");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 20));

        txtCurrentCedula.setEditable(false);
        jPanel3.add(txtCurrentCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 260, 30));

        txtNombre.setEditable(false);
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 260, 30));

        txtNombre2.setEditable(false);
        jPanel3.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 260, 30));

        txtApellido.setEditable(false);
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 260, 30));

        txtApellido2.setEditable(false);
        jPanel3.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 260, 30));

        txtDireccion.setEditable(false);
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 260, 30));

        txtTelefono.setEditable(false);
        jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 260, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Datos del Empleado");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/WhatsApp Image 2022-06-25 at 6.39.58 PM.jpeg"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 560));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 440, 400));

        btnGuardar.setBackground(new java.awt.Color(153, 255, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 75, 30));

        btnAtras.setBackground(new java.awt.Color(153, 255, 204));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 75, 30));

        btnEditar.setBackground(new java.awt.Color(102, 255, 204));
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 90, 30));

        btnNuevo.setBackground(new java.awt.Color(102, 255, 204));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 75, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmpleadoActionPerformed
        Usuario obj_Usuario = new Usuario();
        btnGuardar.setEnabled(false);
        boolean checkUsuario = obj_Usuario.db_SearchEmpleado(txtSearchCedula.getText());
        System.out.println("Usuario encontrado: " + checkUsuario);
        emptyFields();
        //////////////////////////////
        if (txtSearchCedula.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID del Empleado para buscarlo.");
        } else {
            if (checkUsuario) {
                txtCurrentCedula.setEditable(false);
                btnEditar.setEnabled(true);
                disableFields();
                //////////////////////////////
                txtCurrentCedula.setText(obj_Usuario.getCedula());
                txtNombre.setText(obj_Usuario.getNombre1());
                txtNombre2.setText(obj_Usuario.getNombre2());
                txtApellido.setText(obj_Usuario.getApellido1());
                txtApellido2.setText(obj_Usuario.getApellido2());
                cmbAño.setSelectedItem((obj_Usuario.getAño()));
                cmbMes.setSelectedIndex(Integer.parseInt(obj_Usuario.getMes()));
                cmbDia.setSelectedIndex(Integer.parseInt(obj_Usuario.getDia()));
                txtDireccion.setText(obj_Usuario.getDireccion());
                txtTelefono.setText(obj_Usuario.getTelefono());
                //////////////////////////////
            } else {
                emptyFields();
                btnEditar.setEnabled(false);
                JOptionPane.showMessageDialog(this, "El empleado no se encuentra almacenado en la base de datos.\nHaga click en el boton 'Nuevo', llene todos los campos\ny presione el boton 'Guardar'.");
            }

        }

    }//GEN-LAST:event_btnSearchEmpleadoActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMesActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Usuario obj_Usuario = new Usuario();
        boolean checkEmpleado = obj_Usuario.db_SearchEmpleado(txtCurrentCedula.getText());
        System.out.println("Usuario encontrado: " + checkEmpleado);

        if (txtCurrentCedula.getText().length() == 0 || txtNombre.getText().length() == 0 || txtNombre2.getText().length() == 0 || txtApellido.getText().length() == 0 || txtApellido2.getText().length() == 0 || txtDireccion.getText().length() == 0 || txtTelefono.getText().length() == 0 || cmbAño.getSelectedIndex() == 0 || cmbMes.getSelectedIndex() == 0 || cmbDia.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "RELLENE TODOS LOS ESPACIOS!!");
        } else {
            if (checkEmpleado) {
                if (this.getCrear_modificar() == 2) {
                    obj_Usuario.setCedula(txtCurrentCedula.getText());
                    obj_Usuario.setNombre1(txtNombre.getText());
                    obj_Usuario.setNombre2(txtNombre2.getText());
                    obj_Usuario.setApellido1(txtApellido.getText());
                    obj_Usuario.setApellido2(txtApellido2.getText());
                    obj_Usuario.setAño(cmbAño.getItemAt(cmbAño.getSelectedIndex()));
                    obj_Usuario.setMes(cmbMes.getSelectedIndex() + "");
                    obj_Usuario.setDia(cmbDia.getSelectedIndex() + "");
                    obj_Usuario.setDireccion(txtDireccion.getText());
                    obj_Usuario.setTelefono(txtTelefono.getText());
                    obj_Usuario.db_ModifyEmpleado();
                    JOptionPane.showMessageDialog(this, "El empleado fue modificado con éxito!");
                    emptyFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Este empleado, ya se encuentra registrado en la base de datos.");
                    txtCurrentCedula.setText(obj_Usuario.getCedula());
                    txtNombre.setText(obj_Usuario.getNombre1());
                    txtNombre2.setText(obj_Usuario.getNombre2());
                    txtApellido.setText(obj_Usuario.getApellido1());
                    txtApellido2.setText(obj_Usuario.getApellido2());
                    cmbAño.setSelectedItem((obj_Usuario.getAño()));
                    cmbMes.setSelectedIndex(Integer.parseInt(obj_Usuario.getMes()));
                    cmbDia.setSelectedIndex(Integer.parseInt(obj_Usuario.getDia()));
                    txtDireccion.setText(obj_Usuario.getDireccion());
                    txtTelefono.setText(obj_Usuario.getTelefono());

                }

            } else {
                txtCurrentCedula.setEditable(true);
                if (this.getCrear_modificar() == 1) {
                    obj_Usuario.setCedula(txtCurrentCedula.getText());
                    obj_Usuario.setNombre1(txtNombre.getText());
                    obj_Usuario.setNombre2(txtNombre2.getText());
                    obj_Usuario.setApellido1(txtApellido.getText());
                    obj_Usuario.setApellido2(txtApellido2.getText());
                    obj_Usuario.setAño(cmbAño.getItemAt(cmbAño.getSelectedIndex()));
                    obj_Usuario.setMes(cmbMes.getSelectedIndex() + "");
                    obj_Usuario.setDia(cmbDia.getSelectedIndex() + "");
                    obj_Usuario.setDireccion(txtDireccion.getText());
                    obj_Usuario.setTelefono(txtTelefono.getText());
                    obj_Usuario.db_InsertEmpleado();
                    JOptionPane.showMessageDialog(this, "El empleado fue registrado con éxito!");
                    emptyFields();
                } else {
                    JOptionPane.showMessageDialog(this, "Este empleado, ya se encuentra registrado en la base de datos.");
                    txtCurrentCedula.setText(obj_Usuario.getCedula());
                    txtNombre.setText(obj_Usuario.getNombre1());
                    txtNombre2.setText(obj_Usuario.getNombre2());
                    txtApellido.setText(obj_Usuario.getApellido1());
                    txtApellido2.setText(obj_Usuario.getApellido2());
                    cmbAño.setSelectedItem((obj_Usuario.getAño()));
                    cmbMes.setSelectedIndex(Integer.parseInt(obj_Usuario.getMes()));
                    cmbDia.setSelectedIndex(Integer.parseInt(obj_Usuario.getDia()));
                    txtDireccion.setText(obj_Usuario.getDireccion());
                    txtTelefono.setText(obj_Usuario.getTelefono());

                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        frm_Principal frm = new frm_Principal();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cmbAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAñoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        setCrear_modificar(2);
        txtCurrentCedula.setEditable(false);
        EnableFields();
        btnEditar.setEnabled(false);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        setCrear_modificar(1);
        btnEditar.setEnabled(false);
        btnGuardar.setEnabled(true);
        txtCurrentCedula.setEditable(true);
        EnableFields();
        emptyFields();
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_GestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_GestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_GestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_GestionarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_GestionarEmpleado().setVisible(true);
            }
        });
    }

    private int crear_modificar;

    public int getCrear_modificar() {
        return crear_modificar;
    }

    public void setCrear_modificar(int crear_modificar) {
        this.crear_modificar = crear_modificar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSearchEmpleado;
    private javax.swing.JComboBox<String> cmbAño;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCurrentCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtSearchCedula;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
