/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;

import CLASES.Usuario;
import java.awt.Cursor;

/**
 *
 * @author termi
 */
public class frm_Principal extends javax.swing.JFrame {

    Usuario obj_Usuario = new Usuario();
    Cursor poiter = new Cursor(Cursor.HAND_CURSOR);

    public frm_Principal() {
        initComponents();
        lblNombre.setText(obj_Usuario.getCurrentUser());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnCrearUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnVerEmpleado = new javax.swing.JLabel();
        btnCrearPlanilla = new javax.swing.JLabel();
        btnBuscarUsuario = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JLBexit = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 233, 222));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crear Usuario");

        btnCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_add_user_male_96px.png"))); // NOI18N
        btnCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Empleados");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 150, 50));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("+Crear Planilla");
        jLabel6.setAlignmentY(0.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 150, 50));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Usuarios");
        jLabel8.setAlignmentY(0.0F);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 150, 50));

        btnVerEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        btnVerEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVerEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_find_user_male_96px.png"))); // NOI18N
        btnVerEmpleado.setAlignmentY(0.0F);
        btnVerEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerEmpleado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVerEmpleadoMouseMoved(evt);
            }
        });
        btnVerEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerEmpleadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerEmpleadoMouseExited(evt);
            }
        });
        jPanel1.add(btnVerEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 150, 200));

        btnCrearPlanilla.setBackground(new java.awt.Color(0, 0, 0));
        btnCrearPlanilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_insert_table_96px_9.png"))); // NOI18N
        btnCrearPlanilla.setAlignmentY(0.0F);
        btnCrearPlanilla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearPlanilla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCrearPlanillaMouseMoved(evt);
            }
        });
        btnCrearPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPlanillaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearPlanillaMouseExited(evt);
            }
        });
        jPanel1.add(btnCrearPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, 200));

        btnBuscarUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_find_user_male_96px.png"))); // NOI18N
        btnBuscarUsuario.setAlignmentY(0.0F);
        btnBuscarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscarUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnBuscarUsuarioMouseMoved(evt);
            }
        });
        btnBuscarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarUsuarioMouseExited(evt);
            }
        });
        jPanel1.add(btnBuscarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 150, 200));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_user_150px_2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 150, 150));

        lblNombre.setBackground(new java.awt.Color(0, 0, 0));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 51));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Jose Gonzalez");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 325, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo-color-verde-azul-neon-claro-fondo-degradado-borroso-abstracto-plantilla-banner_335640-3440 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 810, 410));

        JLBexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_Close_40px_2.png"))); // NOI18N
        JLBexit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLBexitMouseMoved(evt);
            }
        });
        JLBexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLBexitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLBexitMouseExited(evt);
            }
        });
        jPanel1.add(JLBexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 50, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEmpleadoMouseClicked
        frm_GestionarEmpleado frm = new frm_GestionarEmpleado();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerEmpleadoMouseClicked

    private void btnVerEmpleadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEmpleadoMouseMoved
        btnVerEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnVerEmpleado.setCursor(poiter);
    }//GEN-LAST:event_btnVerEmpleadoMouseMoved

    private void btnVerEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEmpleadoMouseExited
        btnVerEmpleado.setBorder(null);
    }//GEN-LAST:event_btnVerEmpleadoMouseExited

    private void btnCrearPlanillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPlanillaMouseClicked
        frm_CrearPlanilla FRM = new frm_CrearPlanilla();
        FRM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearPlanillaMouseClicked

    private void btnCrearPlanillaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPlanillaMouseMoved
        btnCrearPlanilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCrearPlanilla.setCursor(poiter);
    }//GEN-LAST:event_btnCrearPlanillaMouseMoved

    private void btnCrearPlanillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPlanillaMouseExited
        btnCrearPlanilla.setBorder(null);
    }//GEN-LAST:event_btnCrearPlanillaMouseExited

    private void JLBexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_JLBexitMouseClicked

    private void JLBexitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBexitMouseMoved
        JLBexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        JLBexit.setCursor(poiter);
    }//GEN-LAST:event_JLBexitMouseMoved

    public void setLblName(String userValue) {
        this.lblNombre.setText(userValue);
    }

    private void JLBexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBexitMouseExited
        JLBexit.setBorder(null);
    }//GEN-LAST:event_JLBexitMouseExited

    private void btnBuscarUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioMouseMoved
        btnBuscarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBuscarUsuario.setCursor(poiter);
    }//GEN-LAST:event_btnBuscarUsuarioMouseMoved

    private void btnBuscarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioMouseClicked
        frm_GestionarUsuario obj_GestionarUsuario = new frm_GestionarUsuario();
        obj_GestionarUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBuscarUsuarioMouseClicked

    private void btnBuscarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioMouseExited
        btnBuscarUsuario.setBorder(null);
    }//GEN-LAST:event_btnBuscarUsuarioMouseExited
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBexit;
    private javax.swing.JLabel btnBuscarUsuario;
    private javax.swing.JLabel btnCrearPlanilla;
    private javax.swing.JLabel btnCrearUsuario;
    private javax.swing.JLabel btnVerEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
