/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;

import CLASES.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author termi
 */
public class frm_CrearUsuario extends javax.swing.JFrame {

  /**
   * Creates new form frmCrearUsuario
   */
  public frm_CrearUsuario() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jcAño = new javax.swing.JComboBox<>();
    jcMes = new javax.swing.JComboBox<>();
    jcDia = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    txtCedula = new javax.swing.JTextField();
    txtNombre = new javax.swing.JTextField();
    txtNombre2 = new javax.swing.JTextField();
    txtApellido = new javax.swing.JTextField();
    txtApellido2 = new javax.swing.JTextField();
    txtDireccion = new javax.swing.JTextField();
    txtTelefono = new javax.swing.JTextField();
    btn_atras = new javax.swing.JButton();
    btn_crear = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    txtPassword = new javax.swing.JPasswordField();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Usuario"));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel2.setText("Primer Nombre");
    jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 153, -1, -1));

    jLabel3.setText("Segundo Nombre");
    jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 190, -1, -1));

    jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel4.setText("Primer Apellido");
    jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 233, -1, -1));

    jLabel5.setText("Segundo Apellido");
    jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 273, -1, -1));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel6.setText("Cedula");
    jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 70, 82, -1));

    jLabel7.setText("Fecha de Nacimiento");
    jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 316, -1, -1));

    jcAño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jcAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", " " }));
    jPanel3.add(jcAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 310, -1, -1));

    jcMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jcMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
    jcMes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcMesActionPerformed(evt);
      }
    });
    jPanel3.add(jcMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

    jcDia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jcDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
    jPanel3.add(jcDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 60, -1));

    jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel8.setText("Direccion");
    jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 353, -1, -1));

    jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel9.setText("Telefono");
    jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 401, -1, -1));

    txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 67, 265, -1));

    txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 147, 265, -1));

    txtNombre2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 187, 264, -1));

    txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 227, 264, -1));

    txtApellido2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 267, 264, -1));

    txtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 325, -1));

    txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 325, -1));

    btn_atras.setBackground(new java.awt.Color(51, 255, 204));
    btn_atras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_atras.setText("ATRAS");
    btn_atras.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_atrasActionPerformed(evt);
      }
    });
    jPanel3.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 464, -1, 40));

    btn_crear.setBackground(new java.awt.Color(51, 255, 204));
    btn_crear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    btn_crear.setText("CREAR");
    btn_crear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_crearActionPerformed(evt);
      }
    });
    jPanel3.add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 464, 80, 40));

    jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel1.setText("Password");
    jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, -1, -1));

    txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 107, 265, -1));

    jLabel11.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
    jLabel11.setText("Crear Usuario");
    jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

    jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_eye_40px.png"))); // NOI18N
    jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel12MouseClicked(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        jLabel12MouseExited(evt);
      }
    });
    jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 40));

    jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/WhatsApp Image 2022-06-25 at 6.39.58 PM.jpeg"))); // NOI18N
    jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 480, 530));

    jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 450, 530));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents
    private void jcMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcMesActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jcMesActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
      Usuario obj_Usuario = new Usuario();
      String valuePass = new String(txtPassword.getPassword());

      if (obj_Usuario.Buscar() == true) {//BUSCAR
        JOptionPane.showMessageDialog(this, "Su usuario ya existe ");
      } else {
        if (txtCedula.getText().length() > 0 && valuePass.length() > 0 && txtNombre.getText().length() > 0 && txtNombre2.getText().length() > 0 && txtApellido.getText().length() > 0 && txtApellido2.getText().length() > 0 && txtTelefono.getText().length() > 0 && txtDireccion.getText().length() > 0 && jcDia.getSelectedIndex() > 0 && jcMes.getSelectedIndex() > 0 && jcAño.getSelectedIndex() > 0) {
          if (valuePass.length() > 7) {
            obj_Usuario.setCedula(txtCedula.getText());
            obj_Usuario.setPassword(util.cifrar(String.valueOf(txtPassword.getPassword())));
            obj_Usuario.setNombre1(txtNombre.getText());
            obj_Usuario.setNombre2(txtNombre2.getText());
            obj_Usuario.setApellido1(txtApellido.getText());
            obj_Usuario.setApellido2(txtApellido2.getText());
            obj_Usuario.setAño(jcAño.getItemAt(jcAño.getSelectedIndex()));
            obj_Usuario.setDia(jcDia.getItemAt(jcDia.getSelectedIndex()));
            obj_Usuario.setMes(jcMes.getItemAt(jcMes.getSelectedIndex()));
            obj_Usuario.setDireccion(txtDireccion.getText());
            obj_Usuario.setTelefono(txtTelefono.getText());
    //        obj_Usuario.CrearUsuario();ªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªªcambio
            //------------------------------
            if (obj_Usuario.Buscar()) {//BUSCAR2
              JOptionPane.showMessageDialog(this, "Su usuario se ha insertado con EXITO!");
              frm_Login obj_Login = new frm_Login();
              obj_Login.setVisible(true);
              dispose();
            } else {
              JOptionPane.showMessageDialog(this, "Su usuario no se ha insertado ");
            }
            // fin de BUSCAR2
            //------------------------------
          } else {
            JOptionPane.showMessageDialog(this, "La contraseña debe tener como minimo 8 caracteres.");
          }
        } else {
          JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
        }
      }//FIN DE BUSCAR
    }//GEN-LAST:event_btn_crearActionPerformed
    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
      frm_Principal obj_Principal = new frm_Principal();
      obj_Principal.setVisible(true);
      Usuario obj_Usuario = new Usuario();
      obj_Principal.setLblName(obj_Usuario.getCurrentUser());
      this.dispose();
    }//GEN-LAST:event_btn_atrasActionPerformed
    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
      txtPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
      txtPassword.setEchoChar('*');
    }//GEN-LAST:event_jLabel12MouseExited
  public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new frm_CrearUsuario().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_atras;
  private javax.swing.JButton btn_crear;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JComboBox<String> jcAño;
  private javax.swing.JComboBox<String> jcDia;
  private javax.swing.JComboBox<String> jcMes;
  private javax.swing.JTextField txtApellido;
  private javax.swing.JTextField txtApellido2;
  private javax.swing.JTextField txtCedula;
  private javax.swing.JTextField txtDireccion;
  private javax.swing.JTextField txtNombre;
  private javax.swing.JTextField txtNombre2;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtTelefono;
  // End of variables declaration//GEN-END:variables
}
