/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;

import CLASES.Usuario;
import CLASES.Util;
import CLASES.conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Window;
import javax.swing.JOptionPane;

public class frm_Login extends javax.swing.JFrame {

    private conexion Conn = new conexion();
    private Usuario obj_Usuario = new Usuario();

    public frm_Login() {
        initComponents();
        centreWindow(this);
        this.txt_Password.setEchoChar('*');
    }

    public static void centreWindow(Window frame) {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - frame.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - frame.getHeight()) / 2);
        frame.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Mostrar = new javax.swing.JLabel();
        lbl_Ocultar = new javax.swing.JLabel();
        txt_Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        txt_UserLog = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_Ingresar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        btn_Crear = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Mostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_eye_40px.png"))); // NOI18N
        lbl_Mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_MostrarMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 50, 40));

        lbl_Ocultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Ocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_eye_40px.png"))); // NOI18N
        lbl_Ocultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_OcultarMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_Ocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 50, 40));

        txt_Password.setBackground(new java.awt.Color(153, 255, 204));
        txt_Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Password.setForeground(new java.awt.Color(60, 63, 65));
        txt_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Password.setText("********");
        txt_Password.setBorder(null);
        txt_Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_PasswordMousePressed(evt);
            }
        });
        jPanel1.add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 250, 40));

        jSeparator2.setBackground(new java.awt.Color(51, 0, 255));
        jSeparator2.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 230, 10));

        txt_UserLog.setBackground(new java.awt.Color(153, 255, 204));
        txt_UserLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_UserLog.setForeground(new java.awt.Color(153, 153, 153));
        txt_UserLog.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_UserLog.setText("Ingrese su nombre de usuario");
        txt_UserLog.setBorder(null);
        txt_UserLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_UserLogMousePressed(evt);
            }
        });
        jPanel1.add(txt_UserLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 250, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_user_60px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_key_50px_2.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_user_150px_9.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 0, 150, 150));

        btn_Ingresar.setBackground(new java.awt.Color(102, 255, 102));
        btn_Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 100, 30));

        btn_Salir.setBackground(new java.awt.Color(102, 255, 204));
        btn_Salir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 100, 30));

        btn_Crear.setBackground(new java.awt.Color(102, 255, 204));
        btn_Crear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Crear.setText("+Crear");
        btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/WhatsApp Image 2022-06-25 at 6.39.58 PM.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearActionPerformed
        Frm_CrearUsuario obj_GestU = new Frm_CrearUsuario();
        obj_GestU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_CrearActionPerformed

    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed

        Util obj_encript = new Util();
        String valorPass = new String(txt_Password.getPassword());
        String pssCifred = obj_encript.encode(String.valueOf(valorPass));
        boolean userCheck = obj_Usuario.db_LoginCheck(txt_UserLog.getText(), pssCifred);
        if (userCheck) {
            frm_Principal obj_Principal = new frm_Principal();
            JOptionPane.showMessageDialog(this, "Inicio de sesión satisfactorio.");
            obj_Usuario.setCurrentUser(obj_Usuario.getNombre1() + " " + obj_Usuario.getApellido1());
            obj_Principal.setLblName(obj_Usuario.getCurrentUser());
            obj_Principal.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error de validacion\n Usuario ucontraseña incorrectos.", "Aviso!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void lbl_MostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_MostrarMouseClicked
        lbl_Mostrar.setVisible(false);
        lbl_Ocultar.setVisible(true);
        txt_Password.setEchoChar((char) 0);
    }//GEN-LAST:event_lbl_MostrarMouseClicked

    private void lbl_OcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_OcultarMouseClicked
        lbl_Mostrar.setVisible(true);
        lbl_Ocultar.setVisible(false);
        txt_Password.setEchoChar('*');
    }//GEN-LAST:event_lbl_OcultarMouseClicked

    private void txt_PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_PasswordMousePressed
        if (String.valueOf(txt_Password.getPassword()).equals("********")) {
            txt_Password.setText("");
            txt_Password.setForeground(Color.black);
        }
        if (txt_UserLog.getText().isEmpty()) {
            txt_UserLog.setText("Ingrese su nombre de usuario");
            txt_UserLog.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_PasswordMousePressed

    private void txt_UserLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_UserLogMousePressed
        if (String.valueOf(txt_Password.getPassword()).isEmpty()) {
            txt_Password.setText("********");
            txt_Password.setForeground(Color.gray);
        }
        if (txt_UserLog.getText().equals("Ingrese su nombre de usuario")) {
            txt_UserLog.setText("");
            txt_UserLog.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_UserLogMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Crear;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Mostrar;
    private javax.swing.JLabel lbl_Ocultar;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserLog;
    // End of variables declaration//GEN-END:variables
}
